# Generated by Django 3.1.6 on 2021-02-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20210211_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='nBoleta',
        ),
    ]
